name: Bump Tag

on:
  push:
    branches: ["main"]

jobs:

  # Define an autotagger job that creates tags on changes to main
  bump-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TAG_PAT }}

      # Bump tag according to conventional commit rules
      # See https://www.conventionalcommits.org/en/v1.0.0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # v1.67.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TAG_PAT }}
          RELEASE_BRANCHES: main
          WITH_V: true
          GIT_API_TAGGING: false
          MAJOR_STRING_TOKEN: "BREAKING CHANGE"
          MINOR_STRING_TOKEN: "feat("
          PATCH_STRING_TOKEN: "fix("
          DEFAULT_BUMP: patch
